import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  safeArea: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingBottom: 24,
    alignContent: "center",
    justifyContent: "center",
  },
  keyboardAvoid: {
    flex: 1,
  },
  headerWrap: {
    alignItems: "center",
    marginTop: 16,
    marginBottom: 14,
  },
  logo: {
    width: 44,
    height: 44,
    position: "relative",
    marginBottom: 14,
  },
  logoDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#8fd91c",
    position: "absolute",
  },
  logoTop: {
    top: 0,
    left: 14,
  },
  logoLeft: {
    top: 14,
    left: 0,
  },
  logoRight: {
    top: 14,
    right: 0,
  },
  logoBottom: {
    bottom: 0,
    left: 14,
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    letterSpacing: 0.2,
    color: "#1a2125",
    lineHeight: 50,
    textAlign: "center",
  },
  subtitle: {
    color: "#8a949b",
    fontSize: 16,
    marginTop: 6,
    textAlign: "center",
    marginBottom: 24,
  },
  fieldWrap: {
    marginBottom: 14,
  },
  label: {
    fontSize: 16,
    color: "#243238",
    fontWeight: "700",
    marginBottom: 8,
  },
  inputRow: {
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: "#e8ecef",
    backgroundColor: "#ffffff",
    minHeight: 56,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  inputRowFocused: {
    borderColor: "#94dc2e",
  },
  inputRowError: {
    borderColor: "#ffa7b5",
    shadowColor: "#ff7f99",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 2,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: "#1f2a30",
    paddingVertical: 12,
    marginLeft: 10,
  },
  rightIconButton: {
    paddingLeft: 8,
    paddingVertical: 8,
  },
  primaryButton: {
    marginTop: 6,
    backgroundColor: "#8fd91c",
    borderRadius: 16,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  socialRow: {
    marginTop: 24,
    marginBottom: 24,
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
  },
  socialButton: {
    width: 50,
    height: 50,
    borderRadius: 13,
    borderWidth: 1.2,
    borderColor: "#e8ecef",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  bottomTextRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
    marginTop: 16,
  },
  bottomText: {
    fontSize: 15,
    color: "#4f5d66",
    fontWeight: "500",
  },
  bottomLink: {
    fontSize: 15,
    color: "#87ce1a",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  forgotStandaloneLink: {
    textAlign: "center",
    marginTop: 8,
    fontSize: 15,
    color: "#87ce1a",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  errorBox: {
    marginTop: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ffb7c3",
    backgroundColor: "#fff1f4",
    minHeight: 44,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  errorText: {
    color: "#cf4063",
    fontSize: 13.5,
    fontWeight: "700",
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#f3f5f7",
    justifyContent: "center",
    alignItems: "center",
  },
  forgotHeader: {
    paddingHorizontal: 24,
    paddingTop: 6,
  },
  forgotContent: {
    paddingTop: 6,
  },
  forgotTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: "#1a2125",
    lineHeight: 54,
  },
  forgotSubtitle: {
    fontSize: 16,
    color: "#8a949b",
    marginTop: 6,
    marginBottom: 18,
  },
  methodList: {
    marginBottom: 20,
    gap: 10,
  },
  methodCard: {
    borderRadius: 18,
    borderWidth: 1.2,
    borderColor: "#edf0f2",
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  methodCardActive: {
    borderColor: "#8fd91c",
    shadowColor: "#8fd91c",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 7,
    elevation: 2,
  },
  methodIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#f2f4f6",
    justifyContent: "center",
    alignItems: "center",
  },
  methodIconWrapActive: {
    backgroundColor: "#ecfad0",
  },
  methodTextWrap: {
    flex: 1,
  },
  methodTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1f2a30",
    lineHeight: 28,
  },
  methodCardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1e2a2f",
    marginBottom: 2,
  },
  methodCardSubtitle: {
    color: "#748089",
    fontSize: 13,
    fontWeight: "500",
  },
});
